Let lncm init script create persistent ext4 fs on SD

diff --git a/variant-alpine/etc/init.d/lncm b/variant-alpine/etc/init.d/lncm
--- a/variant-alpine/etc/init.d/lncm
+++ b/variant-alpine/etc/init.d/lncm
@@ -1,33 +1,107 @@
 #!/sbin/openrc-run
-# Copyright 2018 LNCM, distributed under the terms of the GNU General Public License v2
+#
+# Copyright 2018 LNCM
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#    http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 
 depend() {
-        need net
+    need net sshd iotwifi
 }
 
 start() {
-        ebegin "Starting LNCM script"
-	
-        # Persist apks to SD card
-        #/sbin/setup-apkcache /media/mmcblk0p1/cache		
+    ebegin "Starting LNCM installation"
+    # This script will only run once, for persistent installation to SD
 
-	# Add apks listed in /etc/apk/world
-	#/sbin/apk update
-	#/sbin/apk upgrade
+    # Device to partition
+    SD=mmcblk0
 
-	#/etc/init.d/dbus start
-	#/etc/init.d/avahi-daemon start
+    # Offset for second partition
+    START=268M
 
-	# Install docker-compose
-	#/sbin/apk add py3-pip
-	#/usr/bin/pip3 install --upgrade pip
-	#/usr/bin/pip3 install docker-compose
+    if [ -f /media/${SD}p1/installed ]; then
+        echo "Already installed, aborting"
+        exit 1
+    fi
 
-	# Persist config to SD card
-	#/sbin/lbu commit
+    # Fetch current mirror URL
+    #MIR="$(cat /etc/apk/repositories | sed -n 2p)"
 
-	# Backup apkovl.tar.gz to USB storage
-	#/sbin/lbu pkg /media/usb
+    # Check if main mirror is reachable
+    net_check() {
+        ONLINE=$(echo -e 'GET http://dl-cdn.alpinelinux.org/alpine/ HTTP/1.0\n\n' | nc dl-cdn.alpinelinux.org 80 > /dev/null 2>&1; echo $?)
+    }
 
-        eend $?
+    ONLINE=1
+
+    while [ $ONLINE -eq 1 ]
+    do
+        echo "Checking for internet connection..."
+        net_check
+        sleep 1
+    done
+
+    if [ $ONLINE -eq 0 ]; then
+        echo "Online, proceeding with installation"
+
+        echo "Add GNU parted for partitioning"
+        /sbin/apk add parted
+
+        echo "Add ext* filesystem tools"
+        /sbin/apk add e2fsprogs
+
+        echo "Create second primary partition"
+        /usr/sbin/parted -s /dev/$SD mkpart p ext4 $START 100%
+
+        echo "Create ext4 filesystem"
+        /sbin/mkfs.ext4 -F /dev/${SD}p2
+
+        echo "Add ext4 partition to fstab"
+        echo "/dev/${SD}p2 /media/sd ext4 noatime 0 0" >> /etc/fstab
+
+        echo "Create /media/sd"
+        /bin/mkdir /media/sd
+
+        echo "Mount all fstab entries"
+        /bin/mount -a
+
+        echo "Disable LNCM installation script"
+        /sbin/rc-update del lncm default
+
+        echo "Re-mount FAT partition read/write"
+        /bin/mount -o remount,rw /dev/${SD}p1 /media/${SD}p1
+
+        echo "Mark SD card as installed"
+        /bin/touch /media/${SD}p1/installed
+
+        echo "Re-mount FAT partition read-only"
+        /bin/mount -o remount,ro /dev/${SD}p1 /media/${SD}p1
+
+        echo "Persist state to apkovl"
+        /sbin/lbu commit
+        
+        exit 0
+    else
+        echo "No internet connection. Aborting installation!"
+        exit 1
+    fi
+ 
+    # Install docker-compose
+    #/sbin/apk add py3-pip
+    #/usr/bin/pip3 install --upgrade pip
+    #/usr/bin/pip3 install docker-compose
+
+    # Backup apkovl.tar.gz to USB storage
+    #/sbin/lbu pkg /media/usb
+
+    eend $?
 }
