Clean up

diff --git a/etc/init.d/docker-compose b/etc/init.d/docker-compose
--- a/etc/init.d/docker-compose
+++ b/etc/init.d/docker-compose
@@ -8,36 +8,49 @@ depend() {
 
 start() {
   ebegin "Starting docker-compose"
-  if [[ -d /media/important/important/lnd ]]; then
-    if [[ -d /media/archive/archive/bitcoin ]]; then
-      if [[ -f /media/important/important/lnd/lnd.conf ]]; then
-        if [[ -f /media/archive/archive/bitcoin/bitcoin.conf ]]; then
-          cd /home/lncm/compose || exit
-          docker-compose up -d
-        else
-          echo "Bitcoin configuration not found"
-          exit 1
-        fi
-      else
-        echo "LND configuration not found"
-        exit 1
-      fi
-    else
-      echo "Bitcoin directory not found"
-      exit 1
-    fi
-  else
-    echo "LND Directory not found"
+  
+  # Lnd
+  if [ ! -d /media/important/important/lnd ]; then
+    echo "Error: lnd directory not found"
     exit 1
   fi
+    if [ ! -f /media/important/important/lnd/lnd.conf ]; then
+    echo "Error: lnd configuration file not found"
+    exit 1
+  fi
+  
+  # Bitcoind
+  if [ ! -d /media/archive/archive/bitcoin ]; then
+    echo "Error: bitcoind directory not found"
+    exit 1
+  fi
+  if [ ! -f /media/archive/archive/bitcoin/bitcoin.conf ]; then
+    echo "Error: bitcoin directory not found"
+    exit 1
+  fi
+  
+  # Docker compose
+  if [ ! -f /home/lncm/compose ]; then
+    echo "Error: docker compose directory not found!"
+    exit 1
+  fi
+  if [ ! -f /home/lncm/compose/docker-compose.yml ]; then
+    echo "Error: docker compose configuration not found!"
+    exit 1
+  fi
+
+  # All good
+  cd /home/lncm/compose || exit 1
+  docker-compose up -d
+
   eend $?
 }
 
 stop() {
   ebegin "Stopping docker compose"
-  # TODO: block until bitcoind has shut down cleanly
-  /usr/local/sbin/mana stop
-  cd /home/lncm/compose || exit
+  
+  /usr/bin/noma stop && \
+  cd /home/lncm/compose || exit 1
   docker-compose down
 
   eend $?
