Refactor

diff --git a/etc/init.d/lncm-post b/etc/init.d/lncm-post
--- a/etc/init.d/lncm-post
+++ b/etc/init.d/lncm-post
@@ -11,38 +11,55 @@ start() {
   ebegin "Starting LNCM post-installation"
   # This script will only run once, to complete post-installation
 
-  if [ -f /media/mmcblk0p1/installed ]; then
+  check_installed() {
+    if [ -f /media/mmcblk0p1/installed ]; then
+      echo 0
+      return 0
+    else
+      echo 1
+      return 1
+    fi
+  }
+
+  move_cache() {
     echo "Let apk cache live on persistent volume"
     if [ -d /media/mmcblk0p1/cache ]; then
       cp -v /media/mmcblk0p1/cache/* /var/cache/apk/
     fi
     /sbin/setup-apkcache /var/cache/apk
+  }
 
-    echo "Install docker-compose and dependencies for config files"
-    # Install dependencies for docker compose, for generating config files, and to assist with querying containers
+  install_compose() {
+    echo "Install docker-compose and dependencies"
+    # jq for help with parsing JSON
     /sbin/apk update && \
     /sbin/apk add python3 curl jq
 
     /usr/bin/pip3 install --upgrade pip && \
     /usr/bin/pip3 install docker-compose
+  }
 
+  usb_setup() {
     # USB storage setup
     /usr/bin/python3 /usr/local/sbin/lncm-usb.py || exit 1
+  }
 
-    # Verify USB setup succeeded
+  verify_usb() {
+    echo "Verify USB setup"
     if [ ! -d /media/archive ]; then
-      echo 'USB setup failed'
+      echo '"Archive" USB missing'
       exit 1
     elif [ ! -d /media/important ]; then
-      echo 'USB setup failed'
+      echo '"Important" USB missing'
       exit 1
     elif [ ! -d /media/volatile ]; then
-      echo 'USB setup failed'
+      echo '"Volatile" USB missing'
       exit 1
     fi
+  }
 
-    # Generate RPC auth
-    echo "Generate RPC auth from bitcoin repo"
+  fetch_rpcauth() {
+    echo "Generate RPC credentials using rpcauth.py from bitcoin repo"
     curl "https://raw.githubusercontent.com/bitcoin/bitcoin/master/share/rpcauth/rpcauth.py" 2>/dev/null 1>rpcauth.py
     if [ -f ./rpcauth.py ]; then
       chmod 700 rpcauth.py
@@ -50,17 +67,22 @@ start() {
       tail -1 /media/important/important/generated.txt > /media/important/important/rpcpass.txt
       rm rpcauth.py /media/important/important/generated.txt
     else
-      echo "rpcauth not generated - could not reach server"
+      echo "Error: could not reach server"
       exit 1
     fi
+  }
 
+  check_rpc() {
+    echo "Check RPC credentials"
     if [ "$(grep -c rpcauth /media/important/important/rpcauth.txt )" = 0 ]; then
-      echo "Can't generate credentials - exiting!"
+      echo "Error: RPC credentials missing"
       exit 1
     fi
+  }
 
-    # Apply RPC auth
+  generate_rpc() {
     if [ -f /media/important/important/rpcauth.txt ]; then
+      echo "Apply RPC configuration"
       # Replace strings with what was generated
       RPCAUTHLINE="$(cat /media/important/important/rpcauth.txt)"
       GENERATEDPW="$(cat /media/important/important/rpcpass.txt)"
@@ -73,17 +95,24 @@ start() {
       /bin/sed -i "s/RANDOMUSER/lncm/g;"  /home/lncm/compose/docker-compose.yml
       /bin/sed -i "s/RANDOMPASS/$GENERATEDPW/g;"  /home/lncm/compose/docker-compose.yml
     else
-      echo "Error generating config files"
+      echo "Error generating RPC configuration"
       exit 1
     fi
+  }
 
+  install_tor() {
     # Install Tor
-    echo "Installing and starting TOR (and waiting about 10 seconds)"
+    echo "Installing and starting tor (and waiting about 10 seconds)"
     /sbin/apk update && /sbin/apk add tor
     /sbin/service tor start
-    # Add tor to default runlevels
-    /sbin/rc-update add tor default
+  }
 
+  enable_tor() {
+    echo "Add tor to default runlevels"
+    /sbin/rc-update add tor default
+  }
+
+  setup_tor() {
     CHECKTOR_HOSTNAME=1
     # Check to see if Tor generated directory exists
     while [ ! -d /var/lib/tor/lightning ] && [ $CHECKTOR_HOSTNAME -lt 10 ];
@@ -106,73 +135,120 @@ start() {
         echo "Configuring a V2 URI"
         /bin/sed -i "s/; 2 externalip=/externalip=$(cat /var/lib/tor/lightning-tor-v2/hostname)/g; " /home/lncm/lnd/lnd.conf
     fi
+  }
 
-    echo "Checking for existing configs"
+  config_bitcoind() {
+    echo "Checking for existing bitcoind config"
     if [ -f /media/important/important/bitcoin/bitcoin.conf ]; then
       echo "bitcoin.conf exists, making backup and replacing"
       /bin/cp /media/important/important/bitcoin/bitcoin.conf /media/important/important/bitcoin/bitcoin.conf.backup &&
       /bin/cp -f /home/lncm/bitcoin/bitcoin.conf /media/important/important/bitcoin/bitcoin.conf
     else
-      # If not exist copy bitcoin.conf from lncm home directory
+      echo "bitcoind.conf does not exist, creating"
       /bin/cp -f /home/lncm/bitcoin/bitcoin.conf /media/important/important/bitcoin/bitcoin.conf
     fi
+  }
 
+  config_lnd() {
+    echo "Checking for existing lnd config"
     if [ -f /media/important/important/lnd/lnd.conf ]; then
       echo "lnd.conf exists, making backup and replacing"
       /bin/cp /media/important/important/lnd/lnd.conf /media/important/important/lnd/lnd.conf.backup &&
       /bin/cp -f /home/lncm/lnd/lnd.conf /media/important/important/lnd/lnd.conf
     else
-      # If not exist copy lnd.conf from home directory
+      echo "lnd.conf does not exist, creating"
       /bin/cp -f /home/lncm/lnd/lnd.conf /media/important/important/lnd/lnd.conf
     fi
+  }
 
-    # nginx configs
+  config_nginx() {
+    echo "Checking for existing nginx config"
     if [ -f /media/important/important/nginx/nginx.conf ]; then
         echo "nginx.conf exists, making backup and replacing"
         /bin/cp /media/important/important/nginx/nginx.conf /media/important/important/nginx/nginx.conf.backup &&
         /bin/cp -f /home/lncm/nginx/nginx.conf /media/important/important/nginx/nginx.conf
     else
+        echo "nginx.conf does not exist, creating"
         /bin/cp -f /home/lncm/nginx/nginx.conf /media/important/important/nginx/nginx.conf
     fi
+
     if [ -f /media/important/important/nginx/conf.d/default.conf ]; then
         echo "default.conf exists, making backup and replacing"
         /bin/cp /media/important/important/nginx/conf.d/default.conf /media/important/important/nginx/conf.d/default.conf.backup &&
         /bin/cp -f /home/lncm/nginx/conf.d/default.conf /media/important/important/nginx/conf.d/default.conf
     else
+        echo "default.conf does not exists, creating"
         /bin/cp -f /home/lncm/nginx/conf.d/default.conf /media/important/important/nginx/conf.d/default.conf
     fi
+
     if [ -f /media/important/important/nginx/mime.types ]; then
         echo "mime.types exists, making backup and replacing"
         /bin/cp /media/important/important/nginx/mime.types /media/important/important/nginx/mime.types.backup &&
         /bin/cp -f /home/lncm/nginx/mime.types /media/important/important/nginx/mime.types
     else
+        echo "mime.types does not exist, creating"
         /bin/cp -f /home/lncm/nginx/mime.types /media/important/important/nginx/mime.types
     fi
+  }
 
-    echo "Download index.html"
+  fetch_invoicerui() {
+    echo "Fetch invoicer UI"
     if [ ! -f /home/lncm/public_html/index.html ]; then
       cd /home/lncm/public_html || exit
       wget https://raw.githubusercontent.com/lncm/invoicer-ui/master/dist/index.html
     fi
+  }
 
+  install_crontab() {
     echo "Install crontab"
     /usr/bin/crontab /home/lncm/crontab
+  }
 
+  persist_state() {
     echo "Backup apkovl.tar.gz to USB storage"
-    /sbin/lbu pkg /media/important
+    /sbin/lbu package /media/important/important/box.apkovl.tar.gz
+  }
 
+  disable_post() {
     echo "Remove lncm-post from boot"
     /sbin/rc-update del lncm-post default
+  }
 
+  enable_compose() {
     echo "Enable docker-compose at boot"
     /sbin/rc-update add docker-compose default
     /sbin/service docker-compose start
+  }
 
-    exit 0
-  else
-    echo "LNCM persistent installation not found!"
-    exit 1
-  fi
+  main() {
+    is_installed=$(check_installed)
+
+    if [ ! "$is_installed" -eq "0" ]; then
+      echo "Error: LNCM installation not found!"
+      exit 1
+    fi
+
+    move_cache
+    install_compose
+    usb_setup
+    verify_usb
+    fetch_rpcauth
+    check_rpc
+    generate_rpc
+    install_tor
+    enable_tor
+    setup_tor
+    config_bitcoind
+    config_lnd
+    config_nginx
+    fetch_invoicerui
+    install_crontab
+    disable_post
+    enable_compose
+    persist_state
+  }
+
+  main
 
   eend $?
 }
